
CREATE DATABASE test;

CREATE TABLE Users (
	UserID serial PRIMARY KEY,
	Role VARCHAR ( 50 ) UNIQUE NOT NULL,
	TeamType VARCHAR ( 50 ) NOT NULL,
	Email VARCHAR ( 255 ) UNIQUE NOT NULL
)


CREATE TABLE Team (
	ID serial PRIMARY KEY,
	Type VARCHAR ( 255 ) UNIQUE NOT NULL,
	Name VARCHAR ( 255 ) UNIQUE NULL,
	GeoLocation VARCHAR ( 255 ) NOT NULL
)


CREATE TABLE Hub (
	ID serial PRIMARY KEY,
	Name VARCHAR ( 255 ) UNIQUE NOT NULL,
	GeoLocation VARCHAR ( 255 ) NOT NULL
)

